# Generated by Django 4.1.10 on 2023-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_dish_id_dish_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='id',
            new_name='dish_id',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='name',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
