# Generated by Django 4.1.10 on 2023-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_id_dish_dish_id_remove_dish_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('order_status', models.CharField(default='received', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_items', models.ManyToManyField(to='menu.dish')),
            ],
        ),
    ]
